name: publish-to-homebrew

on:
  workflow_call: 
    inputs:
      tag:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

