name: Unit Tests

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run tests
        run: |
          uv sync --no-interaction --dev

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Run tests
        run: |
          uv run pytest
