name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.name }}

      - name: Reset update-changelog branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: debug
        run: |
          git status
          git branch

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "./CHANGELOG.md"
          author_name: Author Name
          author_email: mail@example.com
          committer_name: Committer Name
          committer_email: mail@example.com
          default_author: github_actor
          message: "Your commit message"
          new_branch: custom-new-branch-${{ github.event.release.name }}

      - name: debug
        run: |
          git status
          git branch

      - name: Rebase branch
        run: |
          git rebase origin/main

      - name: Push branch
        run: |
          git push origin custom-new-branch-${{ github.event.release.name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-changelog
          base: main
          title: "Auto update CHANGELOG"
          commit-message: "Auto update CHANGELOG"
          delete-branch: true
