name: Update Changelog Branch

on:
  release:
    types: [published] # Trigger when a release is published

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: minor update
        run: touch test.md
      #   - name: Update Changelog
      #     uses: stefanzweifel/changelog-updater-action@v1
      #     with:
      #       release-notes: ${{ github.event.release.body }} # Add release notes to changelog
      #       latest-version: ${{ github.event.release.name }} # Add latest version to changelog

      # Step 2: Set up GitHub CLI
      - name: Set up GitHub CLI
        uses: actions4gh/setup-gh@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Create the pull request using 'gh' command
      - name: Create Pull Request
        run: |
          gh pr create \
            --base main \
            --head tmp \
            --title "Automated Pull Request from tmp to main" \
            --body "This is an automated pull request created via GitHub Actions."
